services:

  database:
    image: postgres:16.8-alpine3.20
    container_name: react-learning-database
    shm_size: 128mb
    restart: unless-stopped
    env_file:
      - secrets/database/.env
    ports:
      - "5432:5432"
    volumes:
      - react-learning-database:/var/lib/postgresql/data:rw
    networks:
      - react-learning-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    depends_on:
      - database
    image: react-learning-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
      platforms:
        - linux/arm64
        # - linux/amd64
    container_name: react-learning-backend
    ports:
      - "8080:3000"
    env_file:
      - secrets/backend/.env
    networks:
      - react-learning-network

networks:
  react-learning-network:

volumes:
  react-learning-database:
