services:
  backend:
    image: react-learning-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
      platforms:
        - linux/arm64
        # - linux/amd64
    container_name: react-learning-backend
    ports:
      - "8080:3000"
    env_file:
      - secrets/backend/.env
    networks:
      - react-learning-network
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/api/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  react-learning-network:
